name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '2/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Fetch latest data
      run: python scrape.py -s "${{ secrets.STREET }}" -n "${{ secrets.NUMBER }}" -a "${{ secrets.MAILGUN_API_KEY }}"
